name: stale repo identifier

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: stale repo identifier
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - uses: actions/checkout@v4

      - name: Run stale_repos tool
        uses: github/stale-repos@v8.0.0
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ORGANIZATION: ${{ secrets.ORGANIZATION }}
          EXEMPT_TOPICS: "keep,template"
          INACTIVE_DAYS: 365
          ACTIVITY_METHOD: "pushed"
          ADDITIONAL_METRICS: "release,pr"

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v6.0.0
        with:
          title: Stale-repository-report
          content-filepath: ./stale_repos.md
          assignees: natalialuzuriaga
          token: ${{ secrets.GITHUB_TOKEN }}
